name: CRON-Test

on:
  schedule:
    - cron: '3 22 15 5 6'

jobs:
  daily-cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          curl -X "POST" "https://5001c299-7b66-4d9e-a081-42cdd4186c94.mock.pstmn.io/api" \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d $'{ "message": "from Github Actions CRON" }'
