name: CRON-Test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  job-cleanup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X "POST" "https://5001c299-7b66-4d9e-a081-42cdd4186c94.mock.pstmn.io/api" \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d $'{ "message": "from Github Actions CRON" }'
