name: My CRON test

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  daily-cron:
    runs-on: ubuntu-latest
    steps:
      - run: |
         curl -X "https://5001c299-7b66-4d9e-a081-42cdd4186c94.mock.pstmn.io/api" \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d $'{ "message": "Github action CRON Test" }'
